### ISSUE TITLE
Crashes when I try to use it

### ISSUE THREAD

**Issue by disorientedperson** [ywangd/stash#144]
I get this error message whenever I launch StaSh:
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/9BC2C58D-632D-4A13-9539-7CC3C7AA159A/Documents/launch_stash.py", line 36, in <module>
    reload(stash)
  File "/private/var/mobile/Containers/Shared/AppGroup/9BC2C58D-632D-4A13-9539-7CC3C7AA159A/Documents/site-packages/stash/stash.py", line 34, in <module>
    from system.shcommon import IN_PYTHONISTA, ON_IPAD
ImportError: cannot import name IN_PYTHONISTA

**Comment by disorientedperson** [comment]
I can launch StaSh directly, but launch_stash.py is broken.

**Comment by disorientedperson** [comment]
Huh, this stopped happening.
