### ISSUE TITLE
What's the wrong when I install "stash" by pythonista?

### ISSUE THREAD

**Issue by tchy** [ywangd/stash#245]
>>> import requests as r; exec(r.get('http://bit.ly/get-stash').text)
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 1176, in getresponse
    response.begin()
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 284, in begin
    version, status, reason = self._read_status()
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 253, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 377, in send
    timeout=timeout
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/util/retry.py", line 248, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/packages/six.py", line 311, in reraise
    raise value.with_traceback(tb)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 1176, in getresponse
    response.begin()
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 284, in begin
    version, status, reason = self._read_status()
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 253, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/var/containers/Bundle/Application/59699EF3-A79B-4527-9A91-9CFFC403710E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 427, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by Seanld** [comment]
According the errors it's providing, the only thing I can deduce is that the server closing the connection before StaSh is actually being downloaded. This could be because your internet connection is too slow. Check your internet connection, restart Pythonista, and try again. Please tell me if the problem persists.

**Comment by Tossy654** [comment]
try this 🙂
`
import requests as r; exec(r.get('https://raw.githubusercontent.com/ywangd/stash/master/getstash.py').text)
`
