### ISSUE TITLE
Got a problem with installation 

### ISSUE THREAD

**Issue by Jortana** [ywangd/stash#259]
When I use:
import requests as r
exec(r.get('http://bit.ly/get-stash').text)

The file cannot be created correctly 
Here is the trace back:
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 1176, in getresponse
    response.begin()
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 284, in begin
    version, status, reason = self._read_status()
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 245, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 377, in send
    timeout=timeout
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/util/retry.py", line 248, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/packages/six.py", line 311, in reraise
    raise value.with_traceback(tb)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 1176, in getresponse
    response.begin()
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 284, in begin
    version, status, reason = self._read_status()
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/http/client.py", line 245, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/69A27B64-8C28-449F-BDFC-D3DAD298A8AC/Pythonista3/Documents/test.py", line 2, in <module>
    exec(r.get('http://bit.ly/get-stash').text)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/var/containers/Bundle/Application/860AACD4-F9B7-4B2F-BFBA-5D71AB1FAA5F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 427, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

I don’t know why.
Help plz

**Comment by Seanld** [comment]
Check internet connection. If that's not the problem, there may be
something wrong with the server. When it says connection reset by peer, it
usually means the server denied access. Under construction for a few
minutes possibly? OR @ywangd uploaded a new commit at the same time.

**Comment by Jortana** [comment]
My mistake.  I just ran the code via 2.7. It works!

**Comment by Seanld** [comment]
Ah. That would make sense. Interacting with 2.7 scripts via 3.x is messy.
It uses byte objects over strings for networking.
