### ISSUE TITLE
Pip

### ISSUE THREAD

**Issue by JHelfer** [ywangd/stash#353]
Pip isn't working "failed to run setup.py" 

Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.

Every single time, always fails, even when installing modules I know for a fact work in pythonista!!

**Comment by bennr01** [comment]
Hi @JHelfer,
can you please provide the following information:
- some names of the packages you want to install
- the output of `pip --verbose install <pkg>`, where `<pkg>` is the name of the package. Please not the `--verbose` part of the command
- the output of the `version`-command

**Comment by unpin** [comment]
```
[~/Documents]$ pip --verbose install matplotlib
Querying PyPI ... 
Using matplotlib==3.0.3...
A source distribution is available and will be used.
Downloading package ...
Opening: https://files.pythonhosted.org/packages/26/04/8b381d5b166508cc258632b225adbafec49bbe69aa9a4fa1f1b461428313/matplotlib-3.0.3.tar.gz

Save as: /private/var/mobile/Containers/Data/Application/ADDE191D-1CE1-4B5B-A487-72C0D3D82C24/tmp//matplotlib-3.0.3.tar.gz (36640137 bytes)
  36640137  [100.00%]
Extracting archive file ...
Archive extracted.
Running setup file ...
AttributeError('make_release_tree',)
Failed to run setup.py

Traceback (most recent call last):
  File "site-packages/stash/bin/pip.py", line 539, in run
    return self._run_setup_file(setup_filename)
  File "site-packages/stash/bin/pip.py", line 628, in _run_setup_file
    exec(codeobj, namespace, namespace)
  File "/private/var/mobile/Containers/Data/Application/ADDE191D-1CE1-4B5B-A487-72C0D3D82C24/tmp/065cec08a6ff4fb98bdfe08628326903/matplotlib-3.0.3/setup.py", line 43, in <module>
    del sdist.sdist.make_release_tree
AttributeError: make_release_tree

Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
Traceback (most recent call last):
  File "site-packages/stash/bin/pip.py", line 539, in run
    return self._run_setup_file(setup_filename)
  File "site-packages/stash/bin/pip.py", line 628, in _run_setup_file
    exec(codeobj, namespace, namespace)
  File "/private/var/mobile/Containers/Data/Application/ADDE191D-1CE1-4B5B-A487-72C0D3D82C24/tmp/065cec08a6ff4fb98bdfe08628326903/matplotlib-3.0.3/setup.py", line 43, in <module>
AttributeError: make_release_tree

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/stash/bin/pip.py", line 1492, in <module>
    repository.install(pkg_name, ver_spec, dist=dist)
  File "site-packages/stash/bin/pip.py", line 1085, in install
    self._install(pkg_name, pkg_info, archive_filename, dependency_dist=dist)
  File "site-packages/stash/bin/pip.py", line 851, in _install
    files_installed, dependencies = self.installer.run(pkg_name, archive_filename)
  File "site-packages/stash/bin/pip.py", line 575, in run
    raise PipError('Cannot locate packages. Manual installation required.')
PipError: Cannot locate packages. Manual installation required.
```

**Comment by jsbain** [comment]
You cannot install matplotlib.  It is C based, not pure python.  It comes preinstalled with pythonista.  Go ahead and delete anything that did install in site-packages-3, site-packages-2, or site-packages.
