### ISSUE TITLE
Invalid literal installing ics

### ISSUE THREAD

**Issue by holvi-mikael** [ywangd/stash#409]
Installs fine on other platforms. Any workarounds?

```
[~/Documents]$ pip install ics
Querying PyPI ... 
stash: <class 'ValueError'>: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/E94427DA-467A-4A3E-8A3C-59C6EE530946/Pythonista3/Documents/site-packages/stash/system/shruntime.py", line 546, in exec_py_file
    exec (code, namespace, namespace)
  File "site-packages/stash/bin/pip.py", line 1572, in <module>
    repository.install(pkg_name, ver_spec, flags=flags, extras=extras)
  File "site-packages/stash/bin/pip.py", line 1168, in install
    archive_filename, pkg_info = self.download(pkg_name, ver_spec, flags=flags)
  File "site-packages/stash/bin/pip.py", line 1056, in download
    hit = self._determin_hit(pkg_data, ver_spec, flags=flags)
  File "site-packages/stash/bin/pip.py", line 1206, in _determin_hit
    versions = [latest] + _stash.libversion.sort_versions(self._package_releases(pkg_data))
  File "/private/var/mobile/Containers/Shared/AppGroup/E94427DA-467A-4A3E-8A3C-59C6EE530946/Pythonista3/Documents/site-packages/stash/lib/libversion.py", line 120, in sort_versions
    return sorted(versionlist, key=lambda s: Version.parse(s) if isinstance(s, str) else s, reverse=True)
  File "/private/var/mobile/Containers/Shared/AppGroup/E94427DA-467A-4A3E-8A3C-59C6EE530946/Pythonista3/Documents/site-packages/stash/lib/libversion.py", line 120, in <lambda>
    return sorted(versionlist, key=lambda s: Version.parse(s) if isinstance(s, str) else s, reverse=True)
  File "/private/var/mobile/Containers/Shared/AppGroup/E94427DA-467A-4A3E-8A3C-59C6EE530946/Pythonista3/Documents/site-packages/stash/lib/libversion.py", line 166, in parse
    parsed = _parse_version(s)
  File "/private/var/mobile/Containers/Shared/AppGroup/E94427DA-467A-4A3E-8A3C-59C6EE530946/Pythonista3/Documents/site-packages/stash/lib/libversion.py", line 52, in _parse_version
    verparts.append(int(v))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by bennr01** [comment]
This is one of these issues that seem simple at first, but turn out to be extremely annoying.
While the fix is not yet finished, here are some details regarding this issue (warning: slight rant):

Apparently, `ics` gave their first release the version `indev`. Since we want to find the newest release of a package, we must parse all versions first. This is normally not a problem because most packages use PEP440 conform versions. Spoiler: `indev` is not PEP440 compliant.

So, how should one handle this? After reading a bit more trough PEP440, it mandates that we should discard all versions following non-canonical versions. They are even so nice and provide a *little* regex to check if a version is canonical. So, simply check is a version matches the regex and discard it otherwise. Sounds simple, right?

Well, enter code-recycling. You see, there are various situation where we require extremely similar logic. For example, comparing the conditional requirements, for example extra-dependent requirements or python-version-dependent packages. And surprisingly, both of these cases broke after adding the canonical check.

The extra-dependent requirements are a simple case: since the `foo` part of `extra == foo` is not a version, it is not a canonical version.

The python-version dependent packages were more surprising. This is something I would not have noticed if it were not for our tests. You see, we test `pip install` against various packages of varying complexity. Among them is a package called `twisted`. Now, enter the follwing monstrosity:
`"requires_python": ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"`. So, where exactly is the problem? It is in the `*`, which is used for prefix based matching. First, the `*` is not valid in PEP440-canonical versions (they dont match the regex). This is only important due to some suboptimal formulations:

According to PEP345, which regulates  the `python-requires` header, *Version numbers must be in the format specified in Version Specifiers.* and *Each version number must be in the format specified in PEP 440.*. This makes it sound like they must be PEP440 canonical. Well, apparently, PEP440 specifically allows versions with an asterisk, although they are non-canonical. Upon further examination, it appears that PEP345 didn't mean the canonical versions which are the main topic of PEP440, but rather the very specific section *Version matching*. Looking back, it sounds obvious, but a better formulation would have made it easier to discern that they did not refer solely to the part of PEP440 containing the canonical versions.

Anyway, this is why you should always be explicit which part of a specification you are referring to, never make you parsers too lenient and should always follow PEP440-canonical versions.

**Comment by felciano** [comment]
Hi @bennr01 have you looked at https://github.com/ywangd/stash/issues/382? We are running into a similar error when trying to install the Python Dropbox library via Stash, although it doesn't provide the stack trace:

```
StaSh v0.7.5 on python 3.6.1
Warning: you are running StaSh in python3. Some commands may not work correctly in python3.
Please help us improving StaSh by reporting bugs on github.
Tip: You can use the callable StaSh object to issue more commands from a script, e.g. _stash('some_command')
[~/Documents]$ pip install dropbox
Querying PyPI ... 
stash: <class 'ValueError'>: invalid literal for int() with base 10: ''
[~/Documents]$ 
```

I'm wondering if these are duplicates.

**Comment by bennr01** [comment]
@felciano #382 is indeed related. A quick debugging shows that the problem is the string ’"-insert-version-number-here-", which is the version of the firstdropbox` release. The problem is as described above. IIRC, a branch already has a partial fix, which however breaks some other stuff. I haven't touched the related code in a long time, so I'm not sure where exactly the problem is.

**Comment by felciano** [comment]
Thanks @bennr01 that's what I was afraid of. Given the subtleties/edge cases you list above, I wonder whether it is possible to push the decision out to the user? 

Normally I can do e.g. `pip install -Iv dropbox=14.7.0` to be explicit about which version to install. However that doesn't seem to work in `stash`. Is there another way to force a specific version, and thus skip the step of parsing the library history, skipping over weirdness like a version number called `-insert-version-number-here-`?

**Comment by bennr01** [comment]
Normally you'd be able to specify `dropbox==11.7.0`, but this still has to parse all versions (so that `dropbox>=10.0.0` would also work) and is thus also broken.

You could instead either:

- manually get the file url from pypi, download it via `wget` and run pip on the archive file
- try an older version of stash where `pip` version handling was broken in a different way (simply comparing strings as we did back then however would often result in outdated packages being installed).


In the case of the dropbox package, an old version should be preinstalled, so you may not actually need to install it.

**Comment by felciano** [comment]
Thanks @bennr01. Dropbox recently started enforcing short-lived tokens for API access, and the pre-installed version of the Dropbox library doesn't include the functions for checking and refreshing these tokens, hence the need.

I note that `pip versions dropbox` successfully displays all the versions including the weirdly-named ones. Is that because it doesn't actually parse the version label and just displays it?

In any case, I also previously thought manually downloading and installing from the local archive, but couldn't get it to work with either the `wheel` or `tar.gz` downloads. However I might not be doing it right -- the `pip.py` help doesn't document the syntax for doing this. Any errors in what I'm trying below?

```
[~/Documents]$ pip install ~/Documents/dropbox-11.7.0-py3-none-any.whl
Working on GitHub repository ...
stash: <class 'ValueError'>: too many values to unpack (expected 2)
[~/Documents]$ pip install dropbox-11.7.0-py3-none-any.whl
Querying PyPI ... 
Error: Failed to fetch package release urls
[~/Documents]$ pip install dropbox-11.7.0.tar.gz 
Working on Local repository ...
Extracting archive file ...
Archive extracted.
Running setup file ...
AttributeError("'ShIO' object has no attribute 'errors'",)
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
[~/Documents]$ 
```

**Comment by bennr01** [comment]
Seems like this is more broken than it should be...


First of, you can use `stashconf py_traceback 1` to enable full tracebacks, `stashconf py_pdb 1` to enable opening pdb on exception and `pip --verbose ...` for verbose output.


The command to install tar source files looks correct. Not sure about the error. You could possibly extract it into a different directory and run pip on the dir (ensure that a slash is part of t the argument passed to `pip`), but that has a significant chance of failing too.


As for wheels, this may actually work. I don't think I've updated pip to support installing a local `.whl` file, so `pip install *.whl` won't work. But you should be able to bypass `pip` by running `$STASH_ROOT/lib/stashutils/wheels.py` (or similar) directly. See `wheels.py --help` for details. As this bypasses `pip`, a lot of the above bugs shouldn't be encountered. The downside is that you'll have to take care of dependencies and later removal of the package yourself.

**Comment by felciano** [comment]
Thanks @bennr01 this is very helpful. The `.whl` install using `wheels.py` worked for the base `dropbox` library, but I had to use `pip` to install the dependencies by hand as you described.

However now I'm running into errors that are because the new `dropbox` package is importing the pre-loaded python packages instead of the ones I installed via `pip`. For example, via `pip` I've installed `requests 2.25.1`, but when I import the new `dropbox` library, it appears to be using `requests 2.9.1`, which I believe is the pre-loaded one. Is there a way to tell Pythonista to preferentially use the stash-imported libraries?

**Comment by bennr01** [comment]
@felciano

Have you force-quit pythonista after the install of the packages? The pythonista module cache does not empty/reload between execution of scripts, so once an old version of a package has been imported it will be used until pythonista is restarted.


Otherwise, python module load preference is defined in `sys.path` and can also be manipulated from stash using the `$PYTHONPATH` environment variable.


Note that intended behavior (and this *should* still work) is that stash installed packages have priority over the included versions.

**Comment by felciano** [comment]
@bennr01 getting closer. Thanks for the edit to your comment yesterday. There was a stray packaging in the python 3 specific site-packages. Once I cleared that out, I was able to verify that the new dropbox package is loaded from the Pythonista command line, as well as from Stash itself via:

```python3 -c "import dropbox; print(dropbox.__version__)"```

However I'm unable to get this to load correctly from a Pythonista script triggered by a share sheet extension. I have simple test file with a handful of imports (below), and have confirmed that it works when run from Pythonista directly, but exits abruptly at the `import dropbox` call when triggered from a share sheet. Is there something unusual about how modules are imported when run as share sheet?

```
import appex
import importlib
import importlib.util
import datetime
import time
import sys
import io
import clipboard
import logging
import shortcuts
import json
import time
import dialogs
import copy
from urllib.parse import quote
from objc_util import *
from PIL import Image
from pprint import pprint
import requests
print("requests: {}".format(requests.__version__))
import six
print("six: {}".format(six.__version__))
import urllib3
print("urllib3: {}".format(urllib3.__version__))
import dropbox
print("dropbox: {}".format(dropbox.__version__))
sys.exit()
```

**Comment by bennr01** [comment]
@felciano I don't know, though I do know that the share sheet extension has only very limited resources to work with. I don't think `dropbox` would exceed these resource restrictions, but perhaps I'm mistaken. Try removing/commenting out the other imports like PIL.


Overall, this seems like a question that some of the folks on the pythonista forum would know the answer to. Chances are that this is no longer a stash-related problem if it works normally outside of the share sheet.

**Comment by felciano** [comment]
@bennr01 yes I think you are likely right -- seems like either a Pythonista issue or a sharesheet issue (or interaction between the two). But I think the command line test above indicates that the install worked via stash. I'll migrate the rest of this to the forum. Thanks for your help!
