### ISSUE TITLE
Cannot install stash -  bit.ly blocked or not working (TLSV1_ALERT_ACCESS_DENIED)

### ISSUE THREAD

**Issue by mrkeuz** [ywangd/stash#438]
I live in Russia and trying to install Stash by recipe from README.

`import requests as r; exec(r.get('https://bit.ly/get-stash').content)`

But it fails with some unreadable error. Something like related to TLSV1_ALERT_ACCESS_DENIED with many lines of stack trace. (see log below)

Reason is next. `bit.ly` blocked in my country (as I know and for some reason only for some ISP). 
So `bit.ly` cannot resolve URL. In browser, it returns ERR_SSL_PROTOCOL_ERROR. 
Over terminal same behavior (see logs below). 

Over `tor` `bit.ly` working fine and for e.g. over my mobile ISP also working fine.  

Workaround: 

Just resolve `https://bit.ly/get-stash` manually and replace link in installation receipt like this (be careful link may change):
```
import requests as r; exec(r.get('https://raw.githubusercontent.com/ywangd/stash/master/getstash.py').content)
```

This issue added just first for all due to info and workaround. 

PS: Thanks for big work for authors and for all contributors!
Such small "unix-box" is really cool, you can make interesting 
things with it. You're heroes! May the Force be with you! :)

------------------

Wget logs:
```
--2021-04-11 21:59:39--  https://bit.ly/get-stash
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
OpenSSL: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
Unable to establish SSL connection.
```

Pythonista log:
```
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 785, in _validate_conn
    conn.connect()
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connection.py", line 253, in connect
    ssl_version=resolved_ssl_version)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/util/ssl_.py", line 306, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 402, in wrap_socket
    _context=self, _session=session)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 809, in __init__
    self.do_handshake()
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 1062, in do_handshake
    self._sslobj.do_handshake()
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 684, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 377, in send
    timeout=timeout
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/packages/urllib3/connectionpool.py", line 589, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/api.py", line 68, in get
    return request('get', url, params=params, **kwargs)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/api.py", line 54, in request
    return session.request(method=method, url=url, **kwargs)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/sessions.py", line 577, in send
    r = adapter.send(request, **kwargs)
  File "/var/containers/Bundle/Application/EF50408F-1826-4704-9791-546645B2DE8E/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/requests/adapters.py", line 448, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:749)
```

**Comment by Aareon** [comment]
Hi! Can you confirm this works on your end?
```
import requests as r; exec(r.get(r.get('https://unshorten.me/s/bit.ly/get-stash').text[:-1]).content)
```
