### ISSUE TITLE
stash does not run with Pythonista v3.4 Beta

### ISSUE THREAD

**Issue by mkb79** [ywangd/stash#462]
Today [Pythonista v3.4 Beta](https://forum.omz-software.com/topic/7900/what-what-what-new-version-in-testflight) was released. 

When I execute `launch_stash.py` the following issue appears:

```bash
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/04823405-B61A-4EBC-8D72-116EB0824B40/Pythonista3/Documents/launch_stash.py", line 28, in <module>
    from stash import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/04823405-B61A-4EBC-8D72-116EB0824B40/Pythonista3/Documents/site-packages/stash/__init__.py", line 2, in <module>
    from . import core as stash
  File "/private/var/mobile/Containers/Shared/AppGroup/04823405-B61A-4EBC-8D72-116EB0824B40/Pythonista3/Documents/site-packages/stash/core.py", line 23, in <module>
    from .system.shcommon import (_EXTERNAL_DIRS, _STASH_CONFIG_FILES, _STASH_ROOT, _SYS_STDOUT, IN_PYTHONISTA, ON_IPAD)
  File "/private/var/mobile/Containers/Shared/AppGroup/04823405-B61A-4EBC-8D72-116EB0824B40/Pythonista3/Documents/site-packages/stash/system/shcommon.py", line 20, in <module>
    _properties = plistlib.readPlist(os.path.join(os.path.dirname(sys.executable), 'Info.plist'))
AttributeError: module 'plistlib' has no attribute 'readPlist'
```

Maybe there will be any fix in the near future?

**Comment by mkb79** [comment]
I‘ve tried to patch stash myself and opened a new PR #463

**Comment by cclauss** [comment]
Is this closed or not yet?

**Comment by cclauss** [comment]
```
import requests as r; exec(r.get('https://bit.ly/get-stash').content)
```

**Comment by sbbosco** [comment]
This command worked for me:
`url = 'https://raw.githubusercontent.com/ywangd/stash/dev/getstash.py'; import requests as r; exec(r.get(url).text.replace('master', 'dev'))`

**Comment by AltKrypto** [comment]
Seems as though the most recent TestFlight beta changed the name of the site-packages folder which broke pip. I'm guessing here...

Pip install now errors when trying to install packages. 

I'm not talented enough to figure out a fix myself. Can anyone point me in the right direction?

**Comment by AltKrypto** [comment]
![image](https://user-images.githubusercontent.com/84981131/233814642-9253830f-403b-4f63-b05f-f8a4ec5d203e.jpeg)

Here's a screenshot of the error

**Comment by sbbosco** [comment]
@AltKrypto A quick fix that might work for you.

edit `stash/lib/libdist.py` under Python Modules / site-packages (user) to remove '-3'
```
    if six.PY3:
        #SITE_PACKAGES_DIR_NAME = "site-packages-3"
        SITE_PACKAGES_DIR_NAME = "site-packages"
    else:
```

**Comment by AltKrypto** [comment]
> @AltKrypto A quick fix that might work for you.
> 
> 
> 
> edit `stash/lib/libdist.py` under Python Modules / site-packages (user) to remove '-3'
> 
> ```
> 
>     if six.PY3:
> 
>         #SITE_PACKAGES_DIR_NAME = "site-packages-3"
> 
>         SITE_PACKAGES_DIR_NAME = "site-packages"
> 
>     else:
> 
> ```

That did the trick
