### ISSUE TITLE
install eye3d error , "signal only works in main thread"

### ISSUE THREAD

**Issue by amoxuk** [ywangd/stash#469]
[~/Documents]$  pip install eyed3
Collecting eyed3
  Downloading eyeD3-0.9.6-py3-none-any.whl (245 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/commands/install.py", line 339, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_vendor/resolvelib/resolvers.py", line 482, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_vendor/resolvelib/resolvers.py", line 349, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    version=version,
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/candidates.py", line 287, in __init__
    version=version,
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/resolution/resolvelib/candidates.py", line 292, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/operations/prepare.py", line 528, in _prepare_linked_requirement
    link, req.source_dir, self._download, self.download_dir, hashes
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/operations/prepare.py", line 217, in unpack_url
    hashes=hashes,
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/operations/prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/network/download.py", line 143, in __call__
    chunks = _prepare_download(resp, link, self._progress_bar)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/network/download.py", line 68, in _prepare_download
    return DownloadProgressProvider(progress_bar, max=total_length)(chunks)
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/cli/progress_bars.py", line 250, in DownloadProgressProvider
    return BAR_TYPES[progress_bar][0](max=max).iter
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/cli/progress_bars.py", line 165, in __init__
    super().__init__(*args, **kwargs)  # type: ignore
  File "/private/var/mobile/Containers/Shared/AppGroup/46A1F8BD-B085-4EB9-9BC2-A558B7452D9C/Pythonista3/Documents/site-packages-3/pip/_internal/cli/progress_bars.py", line 76, in __init__
    self.original_handler = signal(SIGINT, self.handle_sigint)
  File "/var/containers/Bundle/Application/01375D74-6B82-4A7C-AB3C-649F874BF696/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/signal.py", line 48, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

**Comment by mkb79** [comment]
It seams you have installed pip from PyPI. Please try to use the `pip` command build in stash. Therefore you have to delete the `pip.py` file from `This iPhone\stash_extensions\bin`. Then you can use `pip` for the build in command and `pip3` for the pip version from PyPI.
