### ISSUE TITLE
please delete and reinstall pythonista 3.4 to get stash clean install

### ISSUE THREAD

**Issue by eddo888** [ywangd/stash#488]
old packages can be reinstalled with pip after full clean reinstall and patch of my last three comments

**Comment by ftourand** [comment]
I deleted Pythonista 3.4, then re-install the application.
I ran the installation script for stash
I launch stash and got the following error message (crash):

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/9AAE71A4-9F2B-4E65-AF3A-68F8D516000F/Pythonista3/Documents/launch_stash.py", line 28, in <module>
    from stash import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/9AAE71A4-9F2B-4E65-AF3A-68F8D516000F/Pythonista3/Documents/site-packages/stash/__init__.py", line 2, in <module>
    from . import core as stash
  File "/private/var/mobile/Containers/Shared/AppGroup/9AAE71A4-9F2B-4E65-AF3A-68F8D516000F/Pythonista3/Documents/site-packages/stash/core.py", line 23, in <module>
    from .system.shcommon import (_EXTERNAL_DIRS, _STASH_CONFIG_FILES, _STASH_ROOT, _SYS_STDOUT, IN_PYTHONISTA, ON_IPAD)
  File "/private/var/mobile/Containers/Shared/AppGroup/9AAE71A4-9F2B-4E65-AF3A-68F8D516000F/Pythonista3/Documents/site-packages/stash/system/shcommon.py", line 20, in <module>
    _properties = plistlib.readPlist(os.path.join(os.path.dirname(sys.executable), 'Info.plist'))
AttributeError: module 'plistlib' has no attribute 'readPlist'

Did I forget something ?
Regards
F

**Comment by ftourand** [comment]
I correct the script (_properties … loads().read as specified in other post
Next error : AttributeError: 'Timer' object has no attribute 'isAlive'
Which is already reported as an error
Thks
F

**Comment by cclauss** [comment]
@ftourand's issue was fixed in #485 (merged).
