### ISSUE TITLE
stash doesn't work because of "subprocesses not supported on ios"

### ISSUE THREAD

**Issue by kirillbiktya** [ywangd/stash#502]
Phone model: iPhone 11
iOS version: 16.4.1
Pythonista version: v3.4 (340012)

After successful installation, trying to launch stash and get error:
```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/B14BF70D-DE00-49FE-9393-5D935296DA15/Pythonista3/Documents/launch_stash.py", line 28, in <module>
    from stash import stash
  File "/private/var/mobile/Containers/Shared/AppGroup/B14BF70D-DE00-49FE-9393-5D935296DA15/Pythonista3/Documents/site-packages/stash/__init__.py", line 2, in <module>
    from . import core as stash
  File "/private/var/mobile/Containers/Shared/AppGroup/B14BF70D-DE00-49FE-9393-5D935296DA15/Pythonista3/Documents/site-packages/stash/core.py", line 23, in <module>
    from .system.shcommon import (_EXTERNAL_DIRS, _STASH_CONFIG_FILES, _STASH_ROOT, _SYS_STDOUT, IN_PYTHONISTA, ON_IPAD)
  File "/private/var/mobile/Containers/Shared/AppGroup/B14BF70D-DE00-49FE-9393-5D935296DA15/Pythonista3/Documents/site-packages/stash/system/shcommon.py", line 46, in <module>
    platform_string = platform.platform()
  File "/var/containers/Bundle/Application/46AF8732-568A-4CD0-86E4-23177A79D191/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/platform.py", line 1256, in platform
    system, release = iOS_ver()
  File "/var/containers/Bundle/Application/46AF8732-568A-4CD0-86E4-23177A79D191/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/platform.py", line 464, in iOS_ver
    objc = cdll.LoadLibrary(util.find_library(b'objc'))
  File "/private/var/mobile/Containers/Shared/AppGroup/B14BF70D-DE00-49FE-9393-5D935296DA15/Pythonista3/Documents/site-packages-3/ctypes/util.py", line 302, in find_library
    return _findSoname_ldconfig(name) or \
  File "/private/var/mobile/Containers/Shared/AppGroup/B14BF70D-DE00-49FE-9393-5D935296DA15/Pythonista3/Documents/site-packages-3/ctypes/util.py", line 267, in _findSoname_ldconfig
    with subprocess.Popen(['/sbin/ldconfig', '-p'],
  File "/var/containers/Bundle/Application/46AF8732-568A-4CD0-86E4-23177A79D191/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/subprocess.py", line 764, in __init__
    raise RuntimeError(f"Subprocesses are not supported on {sys.platform}")
RuntimeError: Subprocesses are not supported on ios
```

**Comment by kirillbiktya** [comment]
Sorry, fixed problem by deleting custom ctypes in my site-packages directory
