### ISSUE TITLE
I want to play Python on my iPad

### ISSUE THREAD

**Issue by MINPARKSOO** [ywangd/stash#505]
Hello, I'm someone who came to use pythonista while looking for a Python program that supports gui with an iPad.
I have to use seaborn, matplotlib, stemgraphic
So I downloaded each one through pip install and opened the Python file that I have to open.
But until now, I definitely got the graph I wanted through the console window, but when I suddenly tried it again, I got the following error. Please help me

ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

**Comment by MINPARKSOO** [comment]
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/9B405408-3147-4281-A3D9-EB177BE74744/Pythonista3/Documents/site-packages/numpy/__init__.py", line 125, in <module>
    from numpy.__config__ import show as show_config
ModuleNotFoundError: No module named 'numpy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/2524FB63-D4DD-4D8D-A256-CF7D01F11D1F/File Provider Storage/1111/ex1.2.py", line 1, in <module>
    import seaborn as sns
  File "/private/var/mobile/Containers/Shared/AppGroup/9B405408-3147-4281-A3D9-EB177BE74744/Pythonista3/Documents/site-packages/seaborn/__init__.py", line 2, in <module>
    from .rcmod import *  # noqa: F401,F403
  File "/private/var/mobile/Containers/Shared/AppGroup/9B405408-3147-4281-A3D9-EB177BE74744/Pythonista3/Documents/site-packages/seaborn/rcmod.py", line 3, in <module>
    import matplotlib as mpl
  File "/var/containers/Bundle/Application/D7AEBAE1-F748-4E78-9F6D-0BE4FC9A3C76/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/matplotlib/__init__.py", line 108, in <module>
    from . import cbook, rcsetup
  File "/var/containers/Bundle/Application/D7AEBAE1-F748-4E78-9F6D-0BE4FC9A3C76/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/matplotlib/cbook/__init__.py", line 29, in <module>
    import numpy as np
  File "/private/var/mobile/Containers/Shared/AppGroup/9B405408-3147-4281-A3D9-EB177BE74744/Pythonista3/Documents/site-packages/numpy/__init__.py", line 130, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
